In [33]:
import numpy as np
import math
import copy

In [34]:
number_of_points = 5
degree = 2

lower_bound = 0
upper_bound = 1

def y_cal(x):
    res = np.zeros(len(x), dtype = float)
    for i in range(len(x)):
        a = 1/((2*math.pi)**(-1/2))
        b = math.exp((-x[i]**2)/2)
        res[i] = a*b
    return res

In [35]:
x = np.linspace(lower_bound, upper_bound, number_of_points)
y = y_cal(x)
print(x)
print(y)

[0.   0.25 0.5  0.75 1.  ]
[2.50662827 2.42950743 2.21209169 1.89210229 1.5203469 ]


In [36]:
X = np.zeros((degree + 1, degree + 1), dtype = float)
Y = np.zeros(degree + 1, dtype = float)

for i in range(degree + 1):
    for j in range(degree + 1):
        X[i][j] = np.sum(x**(i + j))
    Y[i] = np.sum(y*x**i)
print(X)
print(Y)

[[5.        2.5       1.875    ]
 [2.5       1.875     1.5625   ]
 [1.875     1.5625    1.3828125]]
[10.56067658  4.65284632  3.28952158]


In [37]:
row, col = X.shape

# Gauss
for i in range(row):
    if X[i, i] == 0:
        for j in range(i + 1, row):
            if X[j, i] != 0:
                C = copy.deepcopy(A[i])
                X[i] = copy.deepcopy(A[j])
                X[j] = C
                C = copy.deepcopy(b[i])
                Y[i] = copy.deepcopy(Y[j])
                Y[j] = C
                break

    Y[i] = Y[i] / X[i, i]
    X[i] = X[i] / X[i, i]
    for j in range(i + 1, row):
        Y[j] = Y[j] - Y[i] * X[j, i]
        X[j] = X[j] - X[i] * X[j, i]
     

# Yackward    
for i in range(row - 1, -1, -1):
    for j in range(i - 1, -1, -1):
        Y[j] = Y[j] - Y[i] * X[j, i]
        X[j] = X[j] - X[i] * X[j, i]
        
print(Y)

[ 2.51529422 -0.21330973 -0.79067742]
