In [17]:
import numpy as np
import math
import copy

In [18]:
number_of_points = 1000
degree = 2

lower_bound = 0
upper_bound = 1

def y_cal(x):
    res = np.zeros(len(x), dtype = float)
    for i in range(len(x)):
        a = 1/((2*math.pi)**(-1/2))
        b = math.exp((-x[i]**2)/2)
        res[i] = a*b
    return res

In [19]:
x = np.linspace(lower_bound, upper_bound, number_of_points)

In [20]:
X = np.zeros((degree + 1, degree + 1), dtype = float)
Y = np.zeros(degree + 1, dtype = float)

for i in range(degree + 1):
    for j in range(degree + 1):
        y = x**(i + j)
        X[i][j] = np.trapz(y, x)
    y = x**i
    Y[i] = np.trapz(y_cal(x)*y, x)

print(X)
print(Y)

[[1.         0.5        0.3333335 ]
 [0.5        0.3333335  0.25000025]
 [0.3333335  0.25000025 0.20000033]]
[2.14473217 0.98628116 0.62438552]


In [21]:
row, col = X.shape

# Gauss
for i in range(row):
    if X[i, i] == 0:
        for j in range(i + 1, row):
            if X[j, i] != 0:
                C = copy.deepcopy(A[i])
                X[i] = copy.deepcopy(A[j])
                X[j] = C
                C = copy.deepcopy(b[i])
                Y[i] = copy.deepcopy(Y[j])
                Y[j] = C
                break

    Y[i] = Y[i] / X[i, i]
    X[i] = X[i] / X[i, i]
    for j in range(i + 1, row):
        Y[j] = Y[j] - Y[i] * X[j, i]
        X[j] = X[j] - X[i] * X[j, i]
     

# Yackward    
for i in range(row - 1, -1, -1):
    for j in range(i - 1, -1, -1):
        Y[j] = Y[j] - Y[i] * X[j, i]
        X[j] = X[j] - X[i] * X[j, i]
        
print(Y)

[ 2.52802284 -0.23370935 -0.79930761]
