In [14]:
import numpy as np
import math

In [15]:
h = 0.1
upper = 1.0
lower = 0.0
x = np.arange(lower, upper+h, h)

z = np.empty([len(x), 3], dtype=float)
z[0] = [-2, 0, 8]

def f_cal(z, t):
    f_vec = np.zeros(len(z))
    f_vec[0] = z[1]
    f_vec[1] = np.exp(-z[1]) + z[0] - np.cos(t)
    f_vec[2] = np.cbrt(z[2]) + z[0] - t*z[1]
    return f_vec


In [16]:
# Euler's method
for i in range(0, len(x)-1):
    z[i+1] = z[i] + h*f_cal(z[i], x[i])

print(z)

[[-2.          0.          8.        ]
 [-2.         -0.2         8.        ]
 [-2.02       -0.37736014  8.002     ]
 [-2.05773601 -0.53152385  8.00756387]
 [-2.1108884  -0.66267878  8.01779899]
 [-2.17715628 -0.77187551  8.03336552]
 [-2.25434383 -0.86096732  8.05452133]
 [-2.34044056 -0.93239049  8.0811983 ]
 [-2.43367961 -0.98886125  8.11309596]
 [-2.53256573 -1.03308272  8.14977495]
 [-2.63587401 -1.06752889  8.19073624]]
